[[xfoil_light]]
arch = "aarch64"
git-tree-sha1 = "ee91907f5a4a85b2c5d9af04b25e66b4598fe5ef"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "02c49a912c76e82541810a061d73bc0b96c7dc2362bcd6eeceece0e642a34e5f"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.0+0/xfoil_light.v0.2.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "aarch64"
git-tree-sha1 = "512b698c61a59ef1821144161d857f53c55251a0"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "57ffd6d3ba682892fea37c69fe8156361b9763cac855b6949f7f9b87128eb77c"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.0+0/xfoil_light.v0.2.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "aarch64"
git-tree-sha1 = "199ad639074cfd865edc2ffae7ff99df40d38498"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "d210fad2d155219ac514a349d938f2b366b3c0272210f01ea0022f04de473e6f"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.0+0/xfoil_light.v0.2.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "aarch64"
git-tree-sha1 = "72f9196796a08b28cf3efbc71ccea9c9c9e9d2dc"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "53e907d0655865e8e98f9fdc3e708c3b930cce203bb576c3f25d6ea747776581"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.0+0/xfoil_light.v0.2.0.aarch64-linux-musl-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "aarch64"
git-tree-sha1 = "01c5eba14b9721e5e237fcc279b8fca895424b19"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "98562374aea13482f45f6a868b7a88d410475c68ecdee3d123916df0f642bf73"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.0+0/xfoil_light.v0.2.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "aarch64"
git-tree-sha1 = "cd8dd0dad086f71f84147573bacfab6429ff64db"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "7ecd632c802ca05e853bdb5489e6de26d097f9bbae7d0892e79a74d5550cbf1d"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.0+0/xfoil_light.v0.2.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8ff91ebf4128c63db7d0235e2be3b48c67c499f9"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "f509f3ec2ea0d33ce6fb1a76b07f1b30cd94c3a95b4eea16b7cbdbff0abd09b7"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.0+0/xfoil_light.v0.2.0.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "86b8d9e1acdce5e17d41eab06ce695666896957b"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "9e4410cf4984a8b78a19aaa77061255defcd20561b4bb8ad248d0379c82df55e"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.0+0/xfoil_light.v0.2.0.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e6d8fd8abf1f164c0eb871679c5ae9bdcab00ddd"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "d8f9c56fe3d99d6a7e8ff6dddb088b7f3046828eba4d2c9c3c5fde01947adde2"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.0+0/xfoil_light.v0.2.0.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "df4d5f1c8ff29cac2fe26da57c5964531af97148"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "60fb75f3a8dff640678e2b4f47465d81d736fb8f426cb1ac67f3aaf1364ce96c"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.0+0/xfoil_light.v0.2.0.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ae5a35ecb4046c1097a1256aa6205acb65cfb3bf"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "19810c0687526ce8730772a733e36dfdb74764f3d3e3d4f2fbc581a6bd8cdb4d"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.0+0/xfoil_light.v0.2.0.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f0516066b87e3453bdf6e90fc6c107d5287178e5"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "35295325c3a8d090f7d0b7474fc5c690c83f9cd3703b7959952aecc4893033a2"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.0+0/xfoil_light.v0.2.0.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "27c5bfc28975ef6cdb86f1a1a1b898b2eb709577"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "19694d1845974df43a045af26a4a14e21694367bc2aba05bfc2e47e0d59f57d6"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.0+0/xfoil_light.v0.2.0.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f6aab45d80594a915a751f8a4fe843376026fb5d"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "860d0b24b72c42a053509965228e5e88f5a684d9dac594132931e6c26c9c10ec"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.0+0/xfoil_light.v0.2.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "81148acc959481c967907f973291cbcf1eea4c14"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "56a2bfda5065004ddb0579803f0ad05cb0365c0ade22015a61eef68c4fcb1109"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.0+0/xfoil_light.v0.2.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c708339edfe9fa0d70c65d5b0340e9b8ffbbee70"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "a6a10a88410fd65f5a9dc768a4432e7f98cd4553af1c69cbf39bfad181af87dd"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.0+0/xfoil_light.v0.2.0.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "25f5124908b61d1d5a724e4b593ea073db24704b"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "8b0d4424f92872394efeeb655f6399d3dea6f84954209d6e949f58ec6eba9237"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.0+0/xfoil_light.v0.2.0.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "54d02cc89a86ca960f6ac98de4fc01c2b2fd210c"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "77a5af21443320ffdc4f04f1d01bae738825028acd675a4f1076c96991712ff9"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.0+0/xfoil_light.v0.2.0.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "i686"
git-tree-sha1 = "8a18dfda6b5c64973bd1b33cf434fa398e572ef1"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "334bb4ffc86ffcb05c7b1779728520e29d9caaaca79e1fca2d5156fcd7734c34"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.0+0/xfoil_light.v0.2.0.i686-linux-gnu-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "i686"
git-tree-sha1 = "2dc19db56294eeb105aedf3d25e52e1b83becf49"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "e159c713b48f715361eff786aab8b410583bb9dd8e835f5deb928fa4f9721332"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.0+0/xfoil_light.v0.2.0.i686-linux-gnu-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "i686"
git-tree-sha1 = "60654ac7364c8655636344098723cf05c7653fb1"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "46dd8b856e32b4bf8d03551fb66eabfb13507224cac834ce90fe1cbab56f6e16"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.0+0/xfoil_light.v0.2.0.i686-linux-gnu-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "i686"
git-tree-sha1 = "3c53dfde684c3bf09b07f7c607cefb35026aa1cc"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "96337ef3f41fefc82f09af2d81e0b40bf33c542f53c47c2f30232f69471e4b64"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.0+0/xfoil_light.v0.2.0.i686-linux-musl-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "i686"
git-tree-sha1 = "8f643fc919348ed3a5d97c9fa665eb9b4b4b220b"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "434c6c425698dd153da9f0b59b28b123a37b8fd1bbe940d68fa8c49d66226d8e"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.0+0/xfoil_light.v0.2.0.i686-linux-musl-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "i686"
git-tree-sha1 = "e0b55a2b36251d73acc0787fe6442346bde572b2"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "1699f7fc142aacb54f70aa351cf96338686513d006fd0d295a34a8681f951468"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.0+0/xfoil_light.v0.2.0.i686-linux-musl-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "i686"
git-tree-sha1 = "5024fe3df0334bdcb70570b787234c14e05d7356"
libgfortran_version = "3.0.0"
os = "windows"

    [[xfoil_light.download]]
    sha256 = "34c15390643f7c3e83f665cb954b26ef6d4571de921c7a0661aa79e1ebf3a75f"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.0+0/xfoil_light.v0.2.0.i686-w64-mingw32-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "i686"
git-tree-sha1 = "8b3fedad60f895d5cd6585bba47c83f56ea4076a"
libgfortran_version = "4.0.0"
os = "windows"

    [[xfoil_light.download]]
    sha256 = "e16f05db9eaa2fc27ed77a7ea9b7f0841e85a4d75e0eda281ffea6ad87bec7b4"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.0+0/xfoil_light.v0.2.0.i686-w64-mingw32-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "i686"
git-tree-sha1 = "daaf313d6b80bce7ce5b9f2f3ce8ef97a703f786"
libgfortran_version = "5.0.0"
os = "windows"

    [[xfoil_light.download]]
    sha256 = "e64b9c5264c8f8895063db7ac81d107d4855052f579b4f41da7322b08eb4c2e0"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.0+0/xfoil_light.v0.2.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "powerpc64le"
git-tree-sha1 = "1d5e781f3768e632cf30915206b8003741ccdfaf"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "16f536a4e57b91131eac1c764b74c6d282c49d11edb72fda4141bfe5972e8d8c"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.0+0/xfoil_light.v0.2.0.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "powerpc64le"
git-tree-sha1 = "73e4c9ec3060385d4e0d184acda193cf15a8ff3c"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "1358675983735aa118b72ee09876cdfeb6a3a9e16993fd194ed4725bfbf7ce79"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.0+0/xfoil_light.v0.2.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "powerpc64le"
git-tree-sha1 = "041550bcdd5682515857f2d92022534163ffeb07"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "10a5cb49865677bb9e38df1ec5ac297149ca5d1eb66ff5ea729a16952c186c9c"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.0+0/xfoil_light.v0.2.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "bac72167ad3fd0b90dc0dc08d566bc5bbeeb7e4b"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "153b58af2f7b9a157669c665e56ce8cfa0ff99a5b4a0279c7d04f16ad3199763"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.0+0/xfoil_light.v0.2.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "773ffa600e87d9bbda80aee7116382aa009df308"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "5822ab126b464c0964a20c7fb6ad1fc81b2adbcdb42fa1c3b1ef92931875654e"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.0+0/xfoil_light.v0.2.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "80c04f0a4b812c32cf2d44bf0741fd83a2325632"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "081ffda5185d8fbc0499ef5b6be6de9918db2562a676879119fee6258cd77ed1"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.0+0/xfoil_light.v0.2.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "22ec0828a105c16e956c46250222204d437310b7"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "66c2499083f9b9ae4d78baa864184452dad29a00e6b520b5c57e581e8bbe1bbd"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.0+0/xfoil_light.v0.2.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "791c81a37e14482da645bc7180650cf98e8ec70c"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "9db1d9046bfc802a7dfcb99cf4c767d00182b20217f10206612361dfdc070556"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.0+0/xfoil_light.v0.2.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "0ecbe692cc187abd7a1d2037ecbe83b18dd3c13b"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "88d21674a59a846cf868ed3d73c9b911124b286b05f2f1b3a5f73a2c20ba4ce5"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.0+0/xfoil_light.v0.2.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "465ef1f1eb3537b873136d117bdfa04dba14b163"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[xfoil_light.download]]
    sha256 = "cf275ac21ad957c38d620de04d64407fabd3dd2b8e944f264249e4c0be47e405"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.0+0/xfoil_light.v0.2.0.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "2a5df9a60a1bf17b8acd230ab6f50e0cb4eb0f31"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[xfoil_light.download]]
    sha256 = "273b0dc9c8d08398f922ec204cf33d0cb02be2a78455aef734ec9908cdef60b1"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.0+0/xfoil_light.v0.2.0.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "a8ccb431d6d8d80a18b18b7f29b2caec25af14b6"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[xfoil_light.download]]
    sha256 = "52b25d4a49e5ebcc079d1ffb4c12700f58c7fd89310ec8809cc874bddd98ed3a"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.0+0/xfoil_light.v0.2.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "0f49a2c5f1c93bd74987d8fc7526fe761be701fb"
libgfortran_version = "3.0.0"
os = "windows"

    [[xfoil_light.download]]
    sha256 = "1ae343eefba05e381ed46620de3a0bd79232785034b80a9f74113b34d5fb408d"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.0+0/xfoil_light.v0.2.0.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "4938fef3037274572482f49b387032ce0523237e"
libgfortran_version = "4.0.0"
os = "windows"

    [[xfoil_light.download]]
    sha256 = "5199d7cf6fb7153045093a2153172b0b8dd83ca16dda50263449bbec7a4aaf05"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.0+0/xfoil_light.v0.2.0.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "147292fd44635de612f5812bec246cd5e31bd397"
libgfortran_version = "5.0.0"
os = "windows"

    [[xfoil_light.download]]
    sha256 = "6d8861a6d8a79b755d2ea09e2b89d1189603d67efbfbe2a56b8e3c1eb6c7f8f6"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.0+0/xfoil_light.v0.2.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
