[[xfoil_light]]
arch = "aarch64"
git-tree-sha1 = "fc799883f3644c862a6db7ddd52a77798223da9c"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "a3348bee149b8afaf01bbabc549b0122ce218195b4e0c1f7fdebc9c702bc6071"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+1/xfoil_light.v0.2.1.aarch64-linux-gnu-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "aarch64"
git-tree-sha1 = "e24cf3a4c6fc64148811b72ff2a9cf0ec5727245"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "086b1bc46758be0daaa58875bada877fc29956aba83d928f7d2b128f9de1bef1"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+1/xfoil_light.v0.2.1.aarch64-linux-gnu-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "aarch64"
git-tree-sha1 = "8a6fdcdf07d53b491584d983843a65ded68d44a2"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "8a78d978a57b451c93da224cc6ffb3b2c701820c62d0a118b6beb3a854355c29"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+1/xfoil_light.v0.2.1.aarch64-linux-gnu-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "aarch64"
git-tree-sha1 = "1d3d7fb20cfc90d45dad76e293261184422d99ec"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "1b2136381ac2a66c77dbfb51e49de5e9ea6550bde8b586e8b6067e0a92da7941"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+1/xfoil_light.v0.2.1.aarch64-linux-musl-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "aarch64"
git-tree-sha1 = "ce56b954b0f98569e5d824a726eb7598d66b1b6d"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "7fcabfccc4ca3db60a42d8f6d6cc701c8a31481450459135a0f59d53460365cc"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+1/xfoil_light.v0.2.1.aarch64-linux-musl-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "aarch64"
git-tree-sha1 = "03f9beca6d273268b34b7e0fa37061966cfecb57"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "29b3e843fb36183d507b20617ca1540210205008897787dc8ad2cdfccb19bc51"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+1/xfoil_light.v0.2.1.aarch64-linux-musl-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "253f07c30927059ed49ec503e2bfa2cf67b84d9e"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "1bf95b72fe0ec96ba71ad4f105d5836d7db0b19925c6b72cbe98c365d43e7673"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+1/xfoil_light.v0.2.1.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1fab39e592e5e9f05baa63287ea4e92c85890b3f"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "4433d88d4a3abb4fb8aedb5e39b7e844daccef7d34e695513c5ba464b9481c31"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+1/xfoil_light.v0.2.1.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5f1b7c72256d01447c401891c2b420312d62b102"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "ccfcf464a30f6abcd2e1f54e00e7870d383bec74471531b47cefd36ac14fdb30"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+1/xfoil_light.v0.2.1.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "dce05ecac011fc57fa35cb2524800f12af6651a4"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "9390d6024335b74e775c171e162ce5ba47b005d00862f4cac2a2a894ec14c966"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+1/xfoil_light.v0.2.1.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9d2abb5106df435c74d9d4137d1cda8adc4d7f9f"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "aea617cfa09390a520a8e4d9d48a69bf13b4031dc1e241ba5538d21a39590145"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+1/xfoil_light.v0.2.1.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "06fb7c2db56ff2bf62c2948cf99dd7773110b732"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "44090486a87f4df7d9b6e29fb5562b060982ef26fcb75516165c54feb1f79ebf"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+1/xfoil_light.v0.2.1.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "70bc0d039978ad7627b70f271c7d22775adf8eda"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "3eae5cc2921e073689e47594605d8151eb167225b36b3b212903cafc0dc0e397"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+1/xfoil_light.v0.2.1.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e8b31b25768f1d0d686806b55e177906392a8b43"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "e119d6561c2657a2c8dd3576693ce6f0c38c4fe994b3cad06ec80ab49d50287f"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+1/xfoil_light.v0.2.1.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "706c53923252346fdc57dce186bd9e722b53ae59"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "28f2c33021a8da1a0dc8bc158648e43c786ec50d7f101da27df878c44844106c"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+1/xfoil_light.v0.2.1.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4f247f3cc6ee83d6e37f26ec8b20046f1c27f746"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "4b75fa85c3d49d435a705075c07173972731dcb18c3abc78c0ebff909e40a8fd"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+1/xfoil_light.v0.2.1.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f34024e9daf95f7ee0c83e59a05212160f179ade"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "07412472677646fdfef1aab5f884e974d67bdba372c9a38e1905ccb873ccdd92"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+1/xfoil_light.v0.2.1.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e7fb7a3dc6b7ec67532c56b5c5f412ade14250ac"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "040aafaf8d37501fcfe0a708d42816b51f7c985486b7748aab834a9f0a8123db"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+1/xfoil_light.v0.2.1.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "i686"
git-tree-sha1 = "b092c141286bde08d0d5e9bd68354fb7bcaf74c9"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "f7f10883a9a409d49ec815d218037bd8946b15b715bc75f64cb6e390f9dcd0a4"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+1/xfoil_light.v0.2.1.i686-linux-gnu-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "i686"
git-tree-sha1 = "d47ecb3a3fa2ea52b4a5ba621aac3cdfcaa02f50"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "533047b4f553cb77d25ed5b77f09f2ac1f8e892fbd97ce0529b49858ec41b808"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+1/xfoil_light.v0.2.1.i686-linux-gnu-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "i686"
git-tree-sha1 = "77501142a51bedf02b30e68203154fb77e87b610"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "583e71cedcab7841034d223a66e461dcd89761571e72682f2290c5f0d79765e0"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+1/xfoil_light.v0.2.1.i686-linux-gnu-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "i686"
git-tree-sha1 = "65fcfdb3a111c009001873cd13800addf1831919"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "776c6854ba520809ab1bd65424a0d0f7a42c7ff2a6d028256e6c485f0bf7da26"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+1/xfoil_light.v0.2.1.i686-linux-musl-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "i686"
git-tree-sha1 = "6c6860a1b577f001ed31746b7510035211666b22"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "746c4a4fbb64e87dc4c55da5ed780187ae25e0aa2625464376d131477d267004"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+1/xfoil_light.v0.2.1.i686-linux-musl-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "i686"
git-tree-sha1 = "a3e032f5ecd48d59dd3bb0e068ad3ed8d702eb21"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "f25f47635ebf293768adda08e34d0804452e090810f54973562f1dd0411f1f3c"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+1/xfoil_light.v0.2.1.i686-linux-musl-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "i686"
git-tree-sha1 = "bb99d0934dcc33e0a6ab0148b7875348b694be49"
libgfortran_version = "3.0.0"
os = "windows"

    [[xfoil_light.download]]
    sha256 = "40f5093b3986c09f7ce5b84029f0f73e17968e2be039a782b01156a05baf5cd1"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+1/xfoil_light.v0.2.1.i686-w64-mingw32-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "i686"
git-tree-sha1 = "8041ca19671fbdeb49b478e42bee08bd6f3def19"
libgfortran_version = "4.0.0"
os = "windows"

    [[xfoil_light.download]]
    sha256 = "e27903756e8228ab27b0f23efbaec676c0f17ac938305f32f223705af4365269"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+1/xfoil_light.v0.2.1.i686-w64-mingw32-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "i686"
git-tree-sha1 = "ce092e0f24d5429c7e0416a7f929b504b6be2dcc"
libgfortran_version = "5.0.0"
os = "windows"

    [[xfoil_light.download]]
    sha256 = "044fc5bced7205e789bc8b0931e2cc3ba6cbd0d06e79e606db0ec698df9e3d00"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+1/xfoil_light.v0.2.1.i686-w64-mingw32-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "powerpc64le"
git-tree-sha1 = "341fc6bc46fb1464ea03e1b7c2d99612e4ea7886"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "cd9ea106a3b6c4a2bf9aa11eb75f558416f175305b9c022c4296c1092cc1c225"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+1/xfoil_light.v0.2.1.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "powerpc64le"
git-tree-sha1 = "adef3a385653015344f48de32512df8808cade94"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "3b7cce1e4c86078ce87d9d74bd09952167db1d82be223a6c95fe5cbf0e78258c"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+1/xfoil_light.v0.2.1.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "powerpc64le"
git-tree-sha1 = "97cdfa5872b7f8b6e8522992c06d9a0fdeb61024"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "ab79b3d2d0dcd650946c43765f2de19042675f9b70ea7c1475fbf2499ee0db50"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+1/xfoil_light.v0.2.1.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "f5c4442ce83edac32cd190710ad14f2417c97267"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "15e6d3570b4784874772f4efd9c7b3c64979f1096cca54a1d8ee58af776c68bb"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+1/xfoil_light.v0.2.1.x86_64-linux-musl-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "26d8e692e50d0d853dec8811d7922527786429ee"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "8875f2effb3e485ee5ad64b86fe19568289b2021720dc5c7c04645eaa716c039"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+1/xfoil_light.v0.2.1.x86_64-linux-musl-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "f44cd29e65cba25aa33429f3f4d4cded7816bbf4"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "f7633113cc0553fd2184f656574593cf8ee0a27dcb3bea620e135a2716a1111e"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+1/xfoil_light.v0.2.1.x86_64-linux-musl-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "86b4dceb62c05a92e02e243cd975575da25097a6"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[xfoil_light.download]]
    sha256 = "58ad05aaf73c6e348163d83a65d443bd60a06feff2d71046a1236603e91006e5"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+1/xfoil_light.v0.2.1.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "2b2f2c6ce397833cd8b81bd2c72b30b02e308fbc"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[xfoil_light.download]]
    sha256 = "a2420129be79356966c94f5149081bf746c7483b28812e3b42d1a914987ab289"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+1/xfoil_light.v0.2.1.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "9a5427e5230977d74c7d7b52453e1bad5e02232c"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[xfoil_light.download]]
    sha256 = "48cf110f2924c64ebd8609c4b1c399bd9db9497534fdc2a3f7b915b7e9a2724c"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+1/xfoil_light.v0.2.1.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "740ab97e36737fcb476264212fcd1ffde3ac8926"
libgfortran_version = "3.0.0"
os = "windows"

    [[xfoil_light.download]]
    sha256 = "d45576ac341c2b817ac39c49beee1a9f2e7749ebafeef6cb1bda702a29bb9bba"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+1/xfoil_light.v0.2.1.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "104abe6729c1b2cc4c5cf890f54864af1bab9ab0"
libgfortran_version = "4.0.0"
os = "windows"

    [[xfoil_light.download]]
    sha256 = "a0c7c5f0aad89e81fa85e5acfb69d1641b464777fa002ad08efe3a7aeab3e4c5"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+1/xfoil_light.v0.2.1.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "e763f1f3f49b6a56a7746f7fd1256b613773ae31"
libgfortran_version = "5.0.0"
os = "windows"

    [[xfoil_light.download]]
    sha256 = "0b8baccaa73eae88fc4bf63bfff7100e3b487a6f4238108c3dc628aa1783ba52"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.1+1/xfoil_light.v0.2.1.x86_64-w64-mingw32-libgfortran5.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "54c965e9eef74e5e5753d23944a94d408669a980"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "a7c84a27d3e7b014525f0d17a5e290638ec4d05010ebe4850584e80992273272"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.3+0/xfoil_light.v0.2.3.x86_64-linux-gnu-libgfortran3.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "fc7cc473157c38b27b28516e37cbd1035ca6b984"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "90bf9aab8b235b07c8d13828442344dd05b3b38ad38ed82b3e024fa91c325068"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.3+0/xfoil_light.v0.2.3.x86_64-linux-gnu-libgfortran4.tar.gz"
[[xfoil_light]]
arch = "x86_64"
git-tree-sha1 = "c66215903ed8a974beb7d710035643f20f2eeb78"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[xfoil_light.download]]
    sha256 = "66f661924788e68506e817098775ba73b12cf4f486516e26dd518a5e1aa9eb9a"
    url = "https://github.com/taylormcd/xfoil_light_jll.jl/releases/download/xfoil_light-v0.2.3+0/xfoil_light.v0.2.3.x86_64-linux-gnu-libgfortran5.tar.gz"
